{% set name = "zstandard" %}
{% set version = "0.11.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3c31da5d78a7b07e722e8a3e0b1295bc9b316b7e90a1666659c451a42750ffe4
  patches:
    - 0001-Use-compiler-from-environment.patch

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - cffi >=1.8
  run:
    - python

test:
  imports:
    - zstandard

about:
  home: https://github.com/indygreg/python-zstandard
  license: BSD 3-Clause
  summary: "Zstandard bindings for Python"
  description: |
    This project provides Python bindings for interfacing with the
    Zstandard compression library. A C extension and CFFI interface are
    provided.
  doc_url: https://github.com/indygreg/python-zstandard/blob/master/README.rst#python-zstandard
  dev_url: https://github.com/indygreg/python-zstandard

extra:
  recipe-maintainers:
    - rmax
    - xhochy
