travis:
  secure:
    BINSTAR_TOKEN: vAU9qXjlqgT9M1/KGImTr6YI6a8gzX2D2s3B8/UIUZiQcHy74uVMmOwk13lqxB8I3+l63UVcwYXfoRuc90QVRK0dfcmUKBSRrOVBSWyxb/6M0Ggh8c7JcCaOPGAF6fb5O3h+sYQgbDWuKHoeJA0/hNscTObSZg240ls5omb2cHUrne7XZCFdlkJ1deCW1vi/LkOkq3TO068HjmJ0NwdZsMTkMpaqUAAvkXK/hFLiI13+u8yeuu8VOjkBas1sjncuxWGJKJmEe9eRWUp9Imh/U5xUMQrjSHleWFzD2qGntjQsAQc2DfM4Q2N/YopoMLvfJuGZg0GFAn45DkfyfYSIpMrVTRQ9ykryBJqBt3PBw/c3NQ2WguJNISwvJPUR1ZQl6u1nfxQmVCO91Tg9RQpQgVlFkzAw4r6zB2LuNHI0aX0vn7omNqL6NLqw41h3x7+xKcmgYh+ryeO4kL7V0sH+553IizJAfENMk5zTR16I5J+/i2L9iPprcfnCMFU2MEjqol4YYN8TnVqYv97Qs/gmegVcIwnT6qNX9okyMlZFmGbeifKAKbYpFnu94YG4aobsC7QBcsOz18vRPrWDWho5WcYem0pKr1qJiZDjbbWMgvWAPk/NhjQZUfdc4cVJGqqTXPwnVhHa5CBN/99CB7pduGYoel8MFb8wCNRYroOiiI8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
